### ISSUE TITLE
react-dnd-preview Preview component does not respect useObservePreviews boolean

### ISSUE THREAD

**Issue by jprosevear** [LouisBrunner/dnd-multi-backend#101]
The dnd-multi-backend Preview component does:
https://github.com/LouisBrunner/dnd-multi-backend/blob/main/packages/react-dnd-multi-backend/src/components/Preview.tsx#L9

**Comment by LouisBrunner** [comment]
`react-dnd-preview` is a standalone package which gives you a convenient way to show dragging drop previews when using  `react-dnd`. For example if you want to use `react-dnd-touch-backend` and show a preview when dragging, this is the package for you.

If you want to use `react-dnd-multi-backend` in order to switch backends based on the user's device, you will need to use the `react-dnd-multi-backend`'s preview components/hooks, which uses `react-dnd-preview` under the hood.

This is working as intended.
