### ISSUE TITLE
Can't use without importing react-dnd and requiring react as a peer dependency

### ISSUE THREAD

**Issue by cormacrelf** [LouisBrunner/dnd-multi-backend#21]
Hi, 

This is some great code, and I'd like to make it work with a new front-end to `dnd-core` that I wrote for Angular. That project is at https://cormacrelf.github.io/angular-skyhook/ & https://github.com/cormacrelf/angular-skyhook/. Edit: it's called `angular-skyhook` now.

Backends in `react-dnd` are not supposed to care about what code provides them with DOM elements to latch onto, and this is true of MultiBackend, except that some some react-specific helpers are bundled into the package. I wouldn't expect that you rebuild those helpers for any other frontend -- the preview component would have to be quite different, and it would mess up your build scripts enormously -- but I would appreciate splitting the package into agnostic and react-specific parts. A major version bump would prevent accidental upgrades. The agnostic part should depend only on `dnd-core`.

**Comment by LouisBrunner** [comment]
Hi,

That's a great idea! I will look into that soon.
Depending on the difficulty, MultiBackend could provide helpers for other frontends (maybe based on pull-requests?).

**Comment by cormacrelf** [comment]
I don’t think there are any other frontends, apart from the time someone renamed it “preact-dnd” and called it a day. But it seems fine in principle. It could work as a Lerna monorepo. That’s how my repo works, and it’ll be really good once Yarn merges a couple of PRs/RFCs for workspaces.

I will have a look into how the React helper works and see if I can make an Angular version.

**Comment by LouisBrunner** [comment]
Thank you for the Lerna suggestion, I didn't know that was the name of the concept/tool.

I just refactored this repository, it is now split in 3 packages:
 - `react-dnd-multi-backend` (same as before)
 - `react-dnd-preview` (just the preview component)
 - `dnd-multi-backend` (the agnostic backend switcher)

You can now use `dnd-multi-backend` instead of `react-dnd-multi-backend` and you won't need React.

If you look at the React package now, you'll see it is just a wrapper around `dnd-multi-backend` and `react-dnd-preview`, as well as a default "pipeline" (HTML5toTouch). I guess that would be a good basis for an helper.

**Comment by cormacrelf** [comment]
Great! Thanks for that! I'll close when I've tested it properly. Expect a PR soon for the angular package.

**Comment by cormacrelf** [comment]
@LouisBrunner I maintain `angular-skyhook-multi-backend` now. It's over at https://github.com/cormacrelf/angular-skyhook as part of a monorepo, and it's best kept there I think. You won't have to manage the ridiculous time-sinking process that is packaging Angular libraries. It is in action driving the examples site.

**Comment by LouisBrunner** [comment]
Great! I updated the documentation on the `next` branch, it will get merged once I get feedback on some React bug fixes.
