### ISSUE TITLE
react-dnd-preview garbage collection?

### ISSUE THREAD

**Issue by jonathan-chin** [LouisBrunner/dnd-multi-backend#296]
I've been playing around with `react-dnd-preview` and it has solved many of my needs. however, I was inspecting the DOM randomly and noticed that span element are being created. this is an issue because a new span element is created for each drag event. here's a screenshot:

![Screenshot 2024-06-27 at 8 10 51 AM](https://github.com/LouisBrunner/dnd-multi-backend/assets/7519412/1d795afd-4d52-4bc3-ae08-65c365d258ba)

my concern is that these spans never get garbage collected. our use case is a fairly large app that's also deployed as a hybrid app. in a browser, the entire dom is reset when the tab is closed or refreshed, which might be ok. but in a hybrid app, it can be running forever (often times people "exit" an app just by backgrounding it) and the dom won't get cleared.

am I using this incorrectly?

**Comment by LouisBrunner** [comment]
Hi @jonathan-chin,

Without any code as reference, it is difficult to tell what is happening. 

If you are using `react-dnd-preview` by itself, this behavior must be due to how you are using the library as that package only handles exposing data from `react-dnd` for easier consumption.

If you are using `react-dnd-multi-backend` with its `DndProvider` (instead of the one from `react-dnd`) then it is possible that there is a fault in the portal code.

If you can give me more details on your usage (and which libraries), I might be able to help. 😄

**Comment by jonathan-chin** [comment]
@LouisBrunner thanks for the follow up! I believe we are using `react-dnd-multi-backend` [here is the file where we're using react-dnd-preview](https://github.com/bilingualgeneration/bili-app/blob/chin-sf1-ui/packages/app/src/components/DnD/Piece.tsx)

and here is the component directory with [all DnD related code](https://github.com/bilingualgeneration/bili-app/tree/chin-sf1-ui/packages/app/src/components/DnD)

we have one more hook that is [managing data related to DnD](https://github.com/bilingualgeneration/bili-app/blob/chin-sf1-ui/packages/app/src/hooks/DnD.tsx)

there's a live version of the code running on the web but it requires creating an account, etc. if having access to the live version would help, let me know and I can set that up.

**Comment by LouisBrunner** [comment]
Ah, that does make a bit more convenient!

Your codebase is still a bit too complex for me to run and try on my own. However, one of the thing I noticed by reading the code is that you render multiple previews (one for each drag handle in `Piece.tsx` and one in `DnD.tsx`). You really only need a single one (the one in `DnD.tsx` should be enough). Maybe that's why you are seeing multiple ones?

As an extra note, `react-dnd-multi-backend` is built to support the presence/absence of the previews based on context, so instead of doing `{!isPlatform('desktop') && <PiecePreview />}`, you can just use `<PiecePreview />` directly and use the `usePreview` from `react-dnd-multi-backend` instead of the one from `react-dnd-preview` (https://github.com/LouisBrunner/dnd-multi-backend/tree/main/packages/react-dnd-multi-backend#hook-based). This shouldn't be related to this issue but it is available as a feature of the package if you which to use it. 😄

**Comment by jonathan-chin** [comment]
thanks @LouisBrunner . let me try and rerun it with a single instance of `react-dnd-preview` and get back to you.

the `isPlatform` check is probably a holdover from when I first implemented the `DragPreviewImage` from stock `react-dnd`. I had to render different previews and backends based on the platform. I haven't fully migrated to `react-dnd-multi-backend` yet; thanks for pointing that out!

**Comment by jonathan-chin** [comment]
cheers! I think removing the extra `react-dnd-preview` in `Piece.tsx` fixed it. thanks so much!
and thanks for building / maintaining this repo!
