### ISSUE TITLE
`TouchTransition` is not adhering to option `enableMouseEvents` passed to `TouchBackend`

### ISSUE THREAD

**Issue by AntonNiklasson** [LouisBrunner/dnd-multi-backend#313]
I'm not sure how, or if, this would work. But it would be nice to have the `TouchTransition` included in this library respond to more than just the `touchstart` event for the transition.

Our config looks like this:

```
const pipeline = {
  backends: [
    {
      id: 'touch',
      backend: TouchBackend,
      transition: TouchTransition,
      preview: false,
      options: {
        enableTouchEvents: true,
        enableMouseEvents: false,
      },
    },
    {
      id: 'keyboard',
      backend: KeyboardBackend,
      context: { window, document },
      transition: KeyboardTransition,
      options: {
        isDragTrigger: isKeyboardDragTrigger,
        preview: false,
      },
    },
  ],
}
```

With the `TouchTransition` only listening for `touchdown` any mouse interaction wouldn't move away from the keyboard backend.

Perhaps we could parametrize the `TouchTransition` and pass some options to it? Or am I missing something?

**Comment by LouisBrunner** [comment]
Hi @AntonNiklasson,

The `options` argument is given to the `backend` so it is not used to configure the `transition` itself.

Currently there isn't any handy way to add multiple transitions to a single backend (bit of an oversight on my part) and each transition can only handle a single event type. So parametrizing wouldn't work either.

I will look into allowing multiple transitions (because it shouldn't be too hard to handle and it's a bit limiting in such a case). In the meantime, you might be able to get away with a slightly more wasteful setup:

```ts
const pipeline = {
  backends: [
    {
      id: 'touch',
      backend: TouchBackend,
      transition: TouchTransition,
      preview: false,
      options: {
        enableTouchEvents: true,
        enableMouseEvents: false,
      },
    },
    {
      id: 'touch-mouse',
      backend: TouchBackend,
      transition: MouseTransition,
      preview: false,
      options: {
        enableTouchEvents: false,
        enableMouseEvents: true,
      },
    },
    {
      id: 'keyboard',
      backend: KeyboardBackend,
      context: { window, document },
      transition: KeyboardTransition,
      options: {
        isDragTrigger: isKeyboardDragTrigger,
        preview: false,
      },
    },
  ],
}
```

**Comment by AntonNiklasson** [comment]
Right, that makes sense. Multiple transitions would be nice, for sure. I think we'll opt for this custom transition in our case:

```
const CustomPointerTransition = createTransition('pointerdown', (event: Event) => {
  const isMouse = 'pointerType' in event && event.pointerType === 'mouse'
  const isTouch = 'touches' in event && isDefined(event.touches)

  return isMouse || isTouch
})
```

The built-in `PointerTransition` here  is actually just checking for a mouse pointer, so I couldn't use that either. I think looking for both touches and and mouse as we do here is what I expected the `PointerTransition` to support, since there's also a `MouseTransition` available.

**Comment by LouisBrunner** [comment]
Well if that works for you, I will hold off extending the library for now.

If you think this transition would have its place next to the existing one, feel free to open a PR. Otherwise creating new transition is exactly the way to handle such issues (I just wasn't sure if there was an event wide enough for you to detect).
