### ISSUE TITLE
Breaking change when combining v6.0.2 with react-dnd v10

### ISSUE THREAD

**Issue by fromi** [LouisBrunner/dnd-multi-backend#50]
Hi,

I just updated my dependencies using yarn upgrade.
I have:
```
    "react-dnd": "^10.0.2",
    "react-dnd-html5-backend": "^10.0.2",
    "react-dnd-multi-backend": "^6.0.1",
    "react-dnd-touch-backend": "^10.0.2",
```
My application is broken: `Error: You must specify a 'backend' property in your Backend entry`
It is fixed after upgrading react-dnd to v11, however it may cause troubles to other people as it is a patch version on your side.

**Comment by LouisBrunner** [comment]
After the upgrade (or any subsequent installation), `yarn` (or `npm`) should prompt you that you are missing a peer dependency:
```
npm WARN react-dnd-multi-backend@6.0.2 requires a peer of react-dnd-html5-backend@^11.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-dnd-multi-backend@6.0.2 requires a peer of react-dnd-touch-backend@^11.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-dnd-preview@6.0.2 requires a peer of react-dnd@^11.1.3 but none is installed. You must install peer dependencies yourself.
```

While this is not ideal, you are still being warned.

Thanks for your feedback though, I will bump the major version for each major change in `react-dnd` in the future in order to avoid such issues.
