### ISSUE TITLE
Reach MenuButton not working when Multi-Backend is active

### ISSUE THREAD

**Issue by aertms** [LouisBrunner/dnd-multi-backend#72]
Hello,
I'm working on a project where I use react-dnd with the react-dnd-multi-backend. I also use the Reach UI [MenuButton](https://reach.tech/menu-button/). But the MenuButton popover is not opening when using touch while I'm using the react-dnd-multi-backend. If I use the react-dnd-touch-backend it is working. I narrowed it down to this package.

I made a small example app to reproduce the problem: [https://codesandbox.io/s/react-dnd-multi-backend-problem-bjwt7?file=/src/App.js](https://codesandbox.io/s/react-dnd-multi-backend-problem-bjwt7?file=/src/App.js). You have to enable the browser developer tools and there open the device toolbar to get touch interactions. With mouse clicks it's working fine.

For comparison I copied the app and used the react-dnd-touch-backend: [https://codesandbox.io/s/react-dnd-touch-backend-working-174vu?file=/src/App.js](https://codesandbox.io/s/react-dnd-touch-backend-working-174vu?file=/src/App.js). Here it's working with touch interactions.

Is this a bug or did I make a mistake somewhere?

**Comment by LouisBrunner** [comment]
Hi @aertms,

Thanks a lot for the example! That is a most peculiar issue... from what I can see you are doing everything as expected and this is a bug.

I would need to dig a bit deeper into `MenuButton` to see why this is happening as this is probably caused by the events shenanigans MultiBackend has to do to allow the switching, I'll get back to you.

**Comment by LouisBrunner** [comment]
@aertms,

I have published `7.0.0-alpha.4` which should resolve your issue.

The problem came from a combination of two sources: browser sending mouse events with touch events and the way MultiBackend does the switching from one backend to another. I either didn't know or forgot that browsers send both touch and mouse events together for all touch events, which meant MultiBackend kept switching between html5 and touch backends. Due to the switching logic, it replayed the `mousedown` event, which triggered `MenuButton` to dismiss the menu right away.

The fix: I added a new transition `PointerTransition` which you should use instead `MouseTransition`, this should avoid MultiBackend switching between the 2 backends all the time (this is also done for you if you use `rdndmb-html5-to-touch` directly).

**Comment by aertms** [comment]
Hi @LouisBrunner,
 Thanks for the quick response! I tested it and it works with the fix! :) Thanks!
